import { useGLTF } from '@react-three/drei';
import React from 'react';

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL + '/models/comission_230717'
  );
  return (
    <group {...props} dispose={null}>
      <skinnedMesh
        geometry={nodes['4_tsuika_gog_tomegu'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_gog_tomegu'].skeleton}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.botan_linkbase.geometry}
        material={materials['マテリアル.005']}
      />
      <skinnedMesh
        geometry={nodes['4_botan'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_botan'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_botan001'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_botan001'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_botan_bag'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_botan_bag'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_kutsunaka'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_kutsunaka'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_kutsuhimo'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_kutsuhimo'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_gogback'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_gogback'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_fronttomegu'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_fronttomegu'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tusika_koshihimo'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tusika_koshihimo'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_koshihimo_back'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_koshihimo_back'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_backtomegu'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_backtomegu'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_sode'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_sode'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_tsuika_gog_parts'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_tsuika_gog_parts'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['4_bag_new'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['4_bag_new'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_ha'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_ha'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_ha_ue'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_ha_ue'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_mayuge'].geometry}
        material={materials.mayuge_matsuge}
        skeleton={nodes['1_mayuge'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_me_'].geometry}
        material={materials.eye}
        skeleton={nodes['1_me_'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_me_hart'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_me_hart'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_me_hoshi'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_me_hoshi'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_me_odoroki'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_me_odoroki'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_shita'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_shita'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['1_te'].geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes['1_te'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_1_karada'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_1_karada'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_antena'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_antena'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_bag'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_bag'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_bag_himo'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_bag_himo'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_boots'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_boots'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_headphone'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_headphone'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_healmet'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_healmet'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_helmet_bou'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_helmet_bou'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['2_himo'].geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes['2_himo'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['3_hair'].geometry}
        material={materials['マテリアル.006']}
        skeleton={nodes['3_hair'].skeleton}
      />
      <primitive object={nodes.root} />
      <skinnedMesh
        geometry={nodes.平面001.geometry}
        material={materials['マテリアル.023']}
        skeleton={nodes.平面001.skeleton}
      />
      <skinnedMesh
        geometry={nodes.平面001_1.geometry}
        material={materials.mayuge_matsuge}
        skeleton={nodes.平面001_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh_6.geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes.Mesh_6.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh_7.geometry}
        material={materials['マテリアル.021']}
        skeleton={nodes.Mesh_7.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh_9.geometry}
        material={materials['マテリアル.005']}
        skeleton={nodes.Mesh_9.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mesh_10.geometry}
        material={materials['マテリアル.021']}
        skeleton={nodes.Mesh_10.skeleton}
      />
    </group>
  );
}

useGLTF.preload(process.env.PUBLIC_URL + '/models/comission_230717');
